//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_saber.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_SaberEntities : DbContext
    {
        public db_SaberEntities()
            : base("name=db_SaberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sys_Error_log> Sys_Error_log { get; set; }
        public DbSet<Sys_Master> Sys_Master { get; set; }
        public DbSet<Sys_Return> Sys_Return { get; set; }
    }
}
