//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_saber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Return
    {
        public string ID { get; set; }
        public string MasterId { get; set; }
        public string DataField { get; set; }
        public string pid { get; set; }
        public string spid { get; set; }
        public string Context { get; set; }
    }
}
