//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_saber.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Master
    {
        public string ID { get; set; }
        public string DataField { get; set; }
        public string user_id { get; set; }
        public string user_name { get; set; }
        public string props { get; set; }
        public string post_id { get; set; }
        public string is_anonym { get; set; }
        public string forum_id { get; set; }
        public string thread_id { get; set; }
        public string contenttext { get; set; }
        public Nullable<int> post_no { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> comment_num { get; set; }
        public Nullable<int> post_index { get; set; }
        public string pb_tpoint { get; set; }
    }
}
